from .staff import *
from .subject import *
from .mainHome import *
from .updateProfile import *
from .profileCreate import *
from .profileVerify import *
from .profileVerifyResend import *
from .faqView import *
from .runCrons import *