from .staff import *
from .subject import *
from .mainHome import *
from .updateProfile import *
from .faqView import *
from .runCrons import *
from .registration import *
from .robotsTxt import *
from .adsTxt import *