# Generated by Django 2.2.10 on 2020-06-06 18:58

from django.db import migrations

def doPython(apps, schema_editor):

    MyModel = apps.get_model('main', 'accountTypes')

    staff=MyModel()
    staff.name="staff"
    staff.save()

    subject=MyModel()
    subject.name="subject"
    subject.save()

def initExperiment(apps, schema_editor):
    MyModel = apps.get_model('main', 'schools')
    
    e=MyModel()
    e.id=1
    e.name="Chapman University"
    e.save()

    e=MyModel()
    e.id=2
    e.name="Demos & Teaching"
    e.save()

    e=MyModel()
    e.id=3
    e.name="Purdue University"
    e.save()

    e=MyModel()
    e.id=4
    e.name="uCal Tech"
    e.save()

    e=MyModel()
    e.id=5
    e.name="University of Arkansas"
    e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(doPython),
        migrations.RunPython(initExperiment),
    ]
