# Generated by Django 2.2.10 on 2020-06-06 21:05

from django.db import migrations

def doPython(apps, schema_editor):

    MyModel = apps.get_model('main', 'majors')

    staff=MyModel()
    staff.name="Economics"
    staff.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200606_2044'),
    ]

    operations = [
        migrations.RunPython(doPython),
    ]
