# Generated by Django 2.2.10 on 2020-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200606_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gradStudent',
            field=models.BooleanField(default=False),
        ),
    ]
