# Generated by Django 2.2.10 on 2020-06-07 21:59

from django.db import migrations

def doPython(apps, schema_editor):

    MyModel = apps.get_model('main', 'experience_levels')

    staff=MyModel()
    staff.name="None"
    staff.save()

    staff=MyModel()
    staff.name="One or More"
    staff.save()

    staff=MyModel()
    staff.name="Any"
    staff.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_studentworker'),
    ]

    operations = [
        migrations.RunPython(doPython),
    ]
