# Generated by Django 2.2.10 on 2020-06-07 22:12

from django.db import migrations

def doPython(apps, schema_editor):
    MyModel = apps.get_model('main', 'subject_types')

    staff=MyModel()
    staff.name="Undergraduate"
    staff.initialValue = True
    staff.save()

    staff=MyModel()
    staff.name="Graduate"
    staff.initialValue = False
    staff.save()

    staff=MyModel()
    staff.name="Non-Student"
    staff.initialValue = False
    staff.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200607_2159'),
    ]

    operations = [
        migrations.RunPython(doPython),
    ]
