# Generated by Django 2.2.10 on 2020-06-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200610_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_day_users',
            name='experiment_session_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ESD', to='main.experiment_session_days'),
        ),
        migrations.AlterField(
            model_name='experiment_session_days',
            name='experiment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ES', to='main.experiment_sessions'),
        ),
        migrations.AlterField(
            model_name='experiment_sessions',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='E', to='main.experiments'),
        ),
    ]
