# Generated by Django 2.2.10 on 2020-06-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200610_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_days',
            name='experiment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ESD', to='main.experiment_sessions'),
        ),
        migrations.AlterField(
            model_name='experiment_sessions',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ES', to='main.experiments'),
        ),
    ]
