# Generated by Django 2.2.10 on 2020-06-16 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200612_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_day_users',
            name='experiment_session_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.experiment_session_days'),
        ),
        migrations.AlterField(
            model_name='experiment_session_days',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
