# Generated by Django 2.2.10 on 2020-06-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200616_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='actual_participants',
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='registration_cutoff',
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='actual_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='registration_cutoff',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='experiment_session_days',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
