# Generated by Django 3.0.7 on 2020-06-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200619_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_sessions',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experience_level_default',
        ),
        migrations.DeleteModel(
            name='experience_levels',
        ),
    ]
