# Generated by Django 3.0.7 on 2020-06-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200624_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiments',
            old_name='experience_max_defualt',
            new_name='experience_max_default',
        ),
        migrations.RenameField(
            model_name='experiments',
            old_name='experience_min_defualt',
            new_name='experience_min_default',
        ),
    ]
