# Generated by Django 3.0.7 on 2020-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200624_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_sessions',
            name='experiments_exclude_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='experiments_include_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='institutions_exclude_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='institutions_include_all',
            field=models.BooleanField(default=True),
        ),
    ]
