# Generated by Django 3.0.7 on 2020-07-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_experiment_sessions_allow_multiple_participatoins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_sessions',
            old_name='allow_multiple_participatoins',
            new_name='allow_multiple_participations',
        ),
    ]
