# Generated by Django 3.0.7 on 2020-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_experiment_sessions_experience_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiments',
            name='allow_multiple_participations_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiments',
            name='experience_constraint_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiments',
            name='experiments_exclude_all_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiments',
            name='experiments_include_all_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiments',
            name='institutions_exclude_all_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiments',
            name='institutions_include_all_default',
            field=models.BooleanField(default=True),
        ),
    ]
