# Generated by Django 3.0.7 on 2020-07-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_hrefexperiments_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='waiverText',
            new_name='consentForm',
        ),
    ]
