# Generated by Django 3.0.7 on 2020-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200720_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='invitationTextMultiDay',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='consentForm',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='invitationText',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
