# Generated by Django 3.0.7 on 2020-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_experiments_invitationtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='cancelationText',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
