# Generated by Django 3.0.7 on 2020-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_parameters_cancelationtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='canceled',
        ),
        migrations.AddField(
            model_name='experiment_sessions',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
