# Generated by Django 3.0.7 on 2020-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200724_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='cancelationTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='invitationTextMultiDaySubject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='invitationTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
