# Generated by Django 3.0.7 on 2020-08-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_experiment_session_days_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiments',
            name='actual_participants_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='allow_multiple_participations_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experience_constraint_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experience_max_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experience_min_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experiments_exclude_all_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experiments_exclude_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experiments_include_all_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='experiments_include_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='gender_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='institutions_exclude_all_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='institutions_exclude_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='institutions_include_all_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='institutions_include_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='registration_cutoff_default',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='subject_type_default',
        ),
        migrations.AddField(
            model_name='experiments',
            name='recruitmentParams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruitmentParameters'),
        ),
    ]
