# Generated by Django 3.0.7 on 2020-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20200815_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Filter',
                'verbose_name_plural': 'Email Filters',
            },
        ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='emailFilters',
        #     field=models.ManyToManyField(to='main.institutions', verbose_name='Email Filters'),
        # ),
    ]
