# Generated by Django 3.0.7 on 2020-08-22 19:58

from django.db import migrations

def doPython(apps, schema_editor):

    MyModel = apps.get_model('main', 'emailFilter')

    m=MyModel()
    m.name="Chapman 1"
    m.domain="chapman.edu"
    m.save()

    m=MyModel()
    m.name="Chapman 2"
    m.domain="mail.chapman.edu"
    m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200822_1947'),
    ]

    operations = [
        migrations.RunPython(doPython),
    ]
