# Generated by Django 3.0.7 on 2020-08-22 21:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('main', '0063_emailfilter_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emailFilter',
            new_name='emailFilters',
        ),
    ]
