# Generated by Django 3.0.7 on 2020-08-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20200822_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emailFilter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.emailFilters', verbose_name='Email Filter'),
        ),
    ]
