# Generated by Django 3.0.7 on 2020-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200825_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentparameters',
            name='schools_exclude',
            field=models.ManyToManyField(blank=True, related_name='recruitmentparameters_schools_exclude', to='main.schools'),
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='schools_exclude_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='schools_include',
            field=models.ManyToManyField(blank=True, related_name='recruitmentparameters_schools_include', to='main.schools'),
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='schools_include_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='actual_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experience_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experiments_exclude_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experiments_include_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='institutions_exclude_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='institutions_include_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='registration_cutoff',
            field=models.IntegerField(default=1),
        ),
    ]
