# Generated by Django 3.0.7 on 2020-08-26 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_profile_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_note',
            old_name='note',
            new_name='text',
        ),
        migrations.AddField(
            model_name='profile_note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_note',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
