# Generated by Django 3.0.7 on 2020-08-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20200828_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='school_legacy',
            new_name='school',
        ),
    ]
