# Generated by Django 3.0.7 on 2020-09-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_parameters_maxannualearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='maxAnnualEarnings',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=5),
        ),
    ]
