# Generated by Django 3.0.7 on 2020-09-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_genders_intialvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genders',
            old_name='intialValue',
            new_name='initialValue',
        ),
    ]
