# Generated by Django 3.0.7 on 2020-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20200917_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genders',
            name='initialValue',
            field=models.BooleanField(default=True),
        ),
    ]
