# Generated by Django 3.0.7 on 2020-09-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20200917_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_types',
            name='initialValue',
            field=models.BooleanField(default=True, verbose_name='Default to On'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='initialValue',
            field=models.BooleanField(default=True, verbose_name='Default to On'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subject_types',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
