# Generated by Django 3.0.7 on 2020-09-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20200917_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='reminderTextText',
            new_name='deactivationText',
        ),
        migrations.AddField(
            model_name='parameters',
            name='deactivationTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='reminderText',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
