# Generated by Django 3.0.7 on 2020-09-19 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #atomic = False

    dependencies = [
        ('main', '0091_auto_20200918_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment_parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_participants', models.IntegerField(default=1)),
                ('registration_cutoff', models.IntegerField(default=1)),
                ('experience_min', models.IntegerField(default=0, null=True)),
                ('experience_max', models.IntegerField(default=1000, null=True)),
                ('experience_constraint', models.BooleanField(default=False)),
                ('institutions_exclude_all', models.BooleanField(default=True)),
                ('institutions_include_all', models.BooleanField(default=True)),
                ('experiments_exclude_all', models.BooleanField(default=True)),
                ('experiments_include_all', models.BooleanField(default=True)),
                ('allow_multiple_participations', models.BooleanField(default=False, null=True)),
                ('schools_include_constraint', models.BooleanField(default=False)),
                ('schools_exclude_constraint', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experiments_exclude', models.ManyToManyField(blank=True, related_name='recruitment_parameters_experiments_exclude', to='main.experiments')),
                ('experiments_include', models.ManyToManyField(blank=True, related_name='recruitment_parameters_experiments_include', to='main.experiments')),
                ('gender', models.ManyToManyField(to='main.genders')),
                ('institutions_exclude', models.ManyToManyField(blank=True, related_name='recruitment_parameters_institutions_exclude', to='main.institutions')),
                ('institutions_include', models.ManyToManyField(blank=True, related_name='recruitment_parameters_institutions_include', to='main.institutions')),
                ('schools_exclude', models.ManyToManyField(blank=True, related_name='recruitment_parameters_schools_exclude', to='main.schools')),
                ('schools_include', models.ManyToManyField(blank=True, related_name='recruitment_parameters_schools_include', to='main.schools')),
                ('subject_type', models.ManyToManyField(to='main.subject_types')),
            ],
            options={
                'verbose_name': 'Recruitment Parameters',
                'verbose_name_plural': 'Recruitment Parameters',
            },
        ),
        migrations.AlterField(
            model_name='experiment_session_invitations',
            name='recruitmentParams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruitment_parameters'),
        ),
        migrations.AlterField(
            model_name='experiment_sessions',
            name='recruitmentParams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruitment_parameters'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='recruitmentParamsDefault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruitment_parameters'),
        ),
        migrations.DeleteModel(
            name='recruitmentParameters',
        ),
    ]
