# Generated by Django 3.0.7 on 2020-09-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0092_auto_20200919_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accountTypes',
            new_name='account_types',
        ),
    ]
