# Generated by Django 3.0.7 on 2020-09-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20200919_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='initialValue',
            field=models.BooleanField(default=False, verbose_name='Default to On'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='schools_include_constraint',
            field=models.BooleanField(default=True),
        ),
    ]
