# Generated by Django 3.0.7 on 2020-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_auto_20200920_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_days',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experiment_session_days',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
