# Generated by Django 3.0.7 on 2020-09-22 19:43

from django.db import migrations

def initGenders(apps, schema_editor):

    MyModel = apps.get_model('main', 'genders')

    gender=MyModel()
    gender.name="Female"
    gender.save()

    gender=MyModel()
    gender.name="Male"
    gender.save()

    gender=MyModel()
    gender.name="Transgender"
    gender.save()

    gender=MyModel()
    gender.name="Other"
    gender.save()

    gender=MyModel()
    gender.name="Prefer not to say"
    gender.save()

def initAccountTypes(apps, schema_editor):

    MyModel = apps.get_model('main', 'account_types')

    staff=MyModel()
    staff.name="staff"
    staff.save()

    subject=MyModel()
    subject.name="subject"
    subject.save()

def initMajors(apps, schema_editor):

    MyModel = apps.get_model('main', 'majors')

    staff=MyModel()
    staff.name="Economics"
    staff.save()

def initEmailFilters(apps, schema_editor):

    MyModel = apps.get_model('main', 'email_filters')

    m=MyModel()
    m.name="Chapman 1"
    m.domain="chapman.edu"
    m.save()

    m=MyModel()
    m.name="Chapman 2"
    m.domain="mail.chapman.edu"
    m.save()

def initSubjectTypes(apps, schema_editor):
    MyModel = apps.get_model('main', 'subject_types')

    staff=MyModel()
    staff.name="Undergraduate"
    staff.save()

    staff=MyModel()
    staff.name="Graduate"
    staff.save()

    staff=MyModel()
    staff.name="Non-Student"
    staff.save()  

def initExperiment(apps, schema_editor):
    MyModel = apps.get_model('main', 'schools')
    
    e=MyModel()
    e.id=1
    e.name="Chapman University"
    e.save()

    e=MyModel()
    e.id=2
    e.name="Demos & Teaching"
    e.save()

    e=MyModel()
    e.id=3
    e.name="Purdue University"
    e.save()

    e=MyModel()
    e.id=4
    e.name="uCal Tech"
    e.save()

    e=MyModel()
    e.id=5
    e.name="University of Arkansas"
    e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20200922_1928'),
    ]

    operations = [
        migrations.RunPython(initGenders),
        migrations.RunPython(initAccountTypes),
        migrations.RunPython(initMajors),
        migrations.RunPython(initEmailFilters),
        migrations.RunPython(initSubjectTypes),
        migrations.RunPython(initExperiment),
    ]
