# Generated by Django 3.0.7 on 2020-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20200922_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consentRequired',
            field=models.BooleanField(default=True, verbose_name='Consent Form Required'),
        ),
        migrations.AlterField(
            model_name='email_filters',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='experiment_session_messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile_note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
