# Generated by Django 3.1.2 on 2020-10-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_auto_20200928_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='chapmanID',
            new_name='studentID',
        ),
    ]
