# Generated by Django 3.1.2 on 2020-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_auto_20201002_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='help_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Name')),
                ('path', models.CharField(default='/', max_length=300, verbose_name='URL Path')),
                ('text', models.CharField(default='', max_length=10000, verbose_name='Help Doc Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Doc',
                'verbose_name_plural': 'Help Docs',
            },
        ),
    ]
