# Generated by Django 3.1.2 on 2020-10-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_auto_20201005_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_session_days',
            old_name='reminderEmailSent',
            new_name='reminder_email_sent',
        ),
    ]
