# Generated by Django 3.1.2 on 2020-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20201006_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentID',
            field=models.CharField(blank=True, default='00000000', max_length=100, null=True, verbose_name='ID Number'),
        ),
    ]
