# Generated by Django 3.1.2 on 2020-11-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_experiment_sessions_invitationtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_sessions',
            old_name='invitationText',
            new_name='invitation_text',
        ),
    ]
