# Generated by Django 3.1.2 on 2020-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_auto_20201126_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='traits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trait',
                'verbose_name_plural': 'Traits',
            },
        ),
    ]
