# Generated by Django 3.1.2 on 2020-11-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_profile_trait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_trait',
            old_name='score',
            new_name='value',
        ),
    ]
