# Generated by Django 3.1.2 on 2020-11-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_auto_20201129_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_trait',
            name='my_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_traits', to='main.profile'),
        ),
    ]
