# Generated by Django 3.1.2 on 2020-12-09 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20201130_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment_parameters_trait_constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.traits')),
                ('recruitment_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recruitment_parameters')),
            ],
            options={
                'verbose_name': 'Recruitment Trait Constraint',
                'verbose_name_plural': 'Recruitment Trait Constraints',
            },
        ),
    ]
