# Generated by Django 3.1.2 on 2020-12-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_recruitment_parameters_trait_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_parameters_trait_constraint',
            name='recruitment_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_constraints', to='main.recruitment_parameters'),
        ),
    ]
