# Generated by Django 3.1.4 on 2020-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20201209_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_parameters',
            name='trait_constraints_require_all',
            field=models.BooleanField(default=False),
        ),
    ]
