# Generated by Django 3.1.4 on 2020-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_recruitment_parameters_trait_constraints_require_all'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile_trait',
            constraint=models.UniqueConstraint(fields=('my_profile', 'trait'), name='unique_PT'),
        ),
    ]
