# Generated by Django 3.1.4 on 2020-12-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_auto_20201214_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_session_days',
            name='enable_time',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='auto_reminder',
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='auto_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
