# Generated by Django 3.1.4 on 2021-01-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_profile_password_reset_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='passwordResetText',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='passwordResetTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
