# Generated by Django 3.1.4 on 2021-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_auto_20210102_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='consentRequired',
            new_name='consent_required',
        ),
    ]
