# Generated by Django 3.1.4 on 2021-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_auto_20210108_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_email_templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(default='', max_length=1000, verbose_name='Subject Text')),
                ('body_text', models.CharField(default='', max_length=10000, verbose_name='Body Text')),
                ('enabled', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitation Email Template',
                'verbose_name_plural': 'Invitation Email Templates',
            },
        ),
    ]
