# Generated by Django 3.1.4 on 2021-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_invitation_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_email_templates',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Subject Text'),
        ),
    ]
