# Generated by Django 3.1.4 on 2021-01-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_invitation_email_templates_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation_email_templates',
            name='subject_text',
        ),
    ]
