# Generated by Django 3.1.4 on 2021-01-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_remove_invitation_email_templates_subject_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='invitationText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='invitationTextMultiDay',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='invitationTextMultiDaySubject',
        ),
    ]
