# Generated by Django 3.1.4 on 2021-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_auto_20210109_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='testEmailAccount',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
