# Generated by Django 3.2 on 2021-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_auto_20210215_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_types',
            options={'ordering': ['display_order'], 'verbose_name': 'Subject Type', 'verbose_name_plural': 'Subject Types'},
        ),
        migrations.AddField(
            model_name='subject_types',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Display order'),
        ),
    ]
