# Generated by Django 3.2 on 2021-09-28 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0147_dailyemailreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemailreport',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
