# Generated by Django 3.2.3 on 2021-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0148_dailyemailreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='max_invitation_block_size',
            field=models.IntegerField(default=100),
        ),
    ]
