# Generated by Django 3.2.3 on 2021-10-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_parameters_max_invitation_block_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_parameters_trait_constraint',
            name='include_if_in_range',
            field=models.BooleanField(default=True),
        ),
    ]
