# Generated by Django 3.2 on 2021-11-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_recruitment_parameters_trait_constraint_include_if_in_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemailreport',
            name='text',
            field=models.CharField(max_length=100000, verbose_name='Text'),
        ),
    ]
