# Generated by Django 3.2 on 2021-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_alter_dailyemailreport_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemailreport',
            name='date',
            field=models.DateField(verbose_name='Date of report'),
        ),
    ]
