# Generated by Django 3.2.11 on 2022-01-28 17:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_alter_dailyemailreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='cancelationText',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='deactivationText',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='emailVerificationResetText',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='passwordResetText',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='reminderText',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
