# Generated by Django 3.2.11 on 2022-01-28 20:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_auto_20220128_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_sessions',
            name='invitation_text',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='invitationText',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='reminderText',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
