# Generated by Django 3.2.11 on 2022-01-28 20:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_auto_20220128_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_email_templates',
            name='body_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Body Text'),
        ),
    ]
