# Generated by Django 3.2.11 on 2022-02-01 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_alter_invitation_email_templates_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_parameters_trait_constraint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitment_parameters_trait_constraint',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
