# Generated by Django 3.2.11 on 2022-02-08 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0156_auto_20220201_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_closed_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_session_days_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_paypal_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_session_days_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_paypal_paysheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_session_days_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_printed_bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_session_days_e', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_printed_paysheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_session_days_d', to=settings.AUTH_USER_MODEL),
        ),
    ]
