# Generated by Django 3.2.11 on 2022-02-09 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0157_auto_20220208_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='user_who_closed_session',
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_closed_session',
            field=models.ManyToManyField(blank=True, related_name='experiment_session_days_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='user_who_paypal_paysheet',
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_paypal_paysheet',
            field=models.ManyToManyField(blank=True, related_name='experiment_session_days_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='user_who_printed_bumps',
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_printed_bumps',
            field=models.ManyToManyField(blank=True, related_name='experiment_session_days_e', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='user_who_printed_paysheet',
        ),
        migrations.AddField(
            model_name='experiment_session_days',
            name='user_who_printed_paysheet',
            field=models.ManyToManyField(blank=True, related_name='experiment_session_days_d', to=settings.AUTH_USER_MODEL),
        ),
    ]
