# Generated by Django 3.2.11 on 2022-02-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_auto_20220209_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_session_days',
            old_name='user_who_paypal_paysheet',
            new_name='users_who_paypal_paysheet',
        ),
        migrations.RenameField(
            model_name='experiment_session_days',
            old_name='user_who_printed_bumps',
            new_name='users_who_printed_bumps',
        ),
        migrations.RenameField(
            model_name='experiment_session_days',
            old_name='user_who_printed_paysheet',
            new_name='users_who_printed_paysheet',
        ),
        migrations.RemoveField(
            model_name='experiment_session_days',
            name='user_who_closed_session',
        ),
    ]
