# Generated by Django 4.0.4 on 2022-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_experiment_session_days_paypal_api_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('pdf_file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
            },
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='experiments_exclude',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_experiments_exclude', to='main.experiments'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='experiments_include',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_experiments_include', to='main.experiments'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='institutions_exclude',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_institutions_exclude', to='main.institutions'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='institutions_include',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_institutions_include', to='main.institutions'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='schools_exclude',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_schools_exclude', to='main.schools'),
        ),
        migrations.AlterField(
            model_name='recruitment_parameters',
            name='schools_include',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_schools_include', to='main.schools'),
        ),
    ]
