# Generated by Django 4.0.4 on 2022-05-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_consentform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='name',
            field=models.CharField(default='Name Here', max_length=300),
        ),
    ]
