# Generated by Django 4.0.4 on 2022-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_alter_consentform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='name',
            field=models.CharField(default='Name Here', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='pdf_file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
