# Generated by Django 4.0.4 on 2022-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_rename_consent_form_defualt_experiments_consent_form_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
