# Generated by Django 4.0.4 on 2022-05-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_alter_consentform_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='consent_required',
            new_name='consent_required_legacy',
        ),
    ]
