# Generated by Django 4.0.4 on 2022-05-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0168_rename_consent_required_profile_consent_required_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='consentForm',
        ),
    ]
