# Generated by Django 4.0.4 on 2022-05-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0169_remove_parameters_consentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms_b', to='main.consentform')),
                ('my_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms_a', to='main.profile')),
            ],
            options={
                'verbose_name': 'Profile Consent Form',
                'verbose_name_plural': 'Profile Consent Forms',
            },
        ),
    ]
