# Generated by Django 4.0.4 on 2022-05-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0170_profileconsentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconsentform',
            name='consent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_consent_forms_b', to='main.consentform'),
        ),
        migrations.AlterField(
            model_name='profileconsentform',
            name='my_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_consent_forms_a', to='main.profile'),
        ),
    ]
