# Generated by Django 4.0.4 on 2022-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0171_alter_profileconsentform_consent_form_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profileconsentform',
            constraint=models.UniqueConstraint(fields=('my_profile', 'consent_form'), name='unique_profile_consent_form'),
        ),
    ]
