# Generated by Django 4.0.4 on 2022-05-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_remove_experiment_session_day_users_experiment_session_legacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentform',
            options={'ordering': ['name'], 'verbose_name': 'Consent Form', 'verbose_name_plural': 'Consent Forms'},
        ),
    ]
