# Generated by Django 4.0.4 on 2022-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0175_profileconsentform_singnature_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='signature_required',
            field=models.BooleanField(default=True),
        ),
    ]
