# Generated by Django 4.0.4 on 2022-06-05 00:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_consentform_signature_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileconsentform',
            name='singnature_resolution',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
