# Generated by Django 4.0.4 on 2022-06-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0177_profileconsentform_singnature_resolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileconsentform',
            old_name='singnature_points',
            new_name='signature_points',
        ),
    ]
