# Generated by Django 4.0.5 on 2022-06-08 00:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_rename_singnature_points_profileconsentform_signature_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_page_notice',
            name='body_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='help_docs',
            name='text',
            field=tinymce.models.HTMLField(default='', verbose_name='Help Doc Text'),
        ),
    ]
