# Generated by Django 4.0.5 on 2022-06-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_alter_front_page_notice_body_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='agreement_required',
            field=models.BooleanField(default=True),
        ),
    ]
