# Generated by Django 4.0.6 on 2022-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0183_experiment_sessions_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
