# Generated by Django 4.0.6 on 2022-07-15 20:58

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0185_alter_experiment_session_days_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_trait',
            options={'ordering': [django.db.models.functions.text.Lower('trait__name')], 'verbose_name': 'Profile Trait', 'verbose_name_plural': 'Profile Traits'},
        ),
    ]
