# Generated by Django 4.0.6 on 2022-07-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0190_alter_experiments_consent_form_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
