# Generated by Django 4.0.6 on 2022-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0193_alter_profileconsentform_options_consentform_irb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='agreement_text',
            field=models.CharField(default='I have read the above information, understand it fully and have had any questions regarding the study answered to my satisfaction. I consent to participate in the research and agree to participate in the study.', max_length=300),
        ),
        migrations.AddField(
            model_name='consentform',
            name='link_text',
            field=models.CharField(default='View Consent Form', max_length=300),
        ),
        migrations.AddField(
            model_name='consentform',
            name='title_text',
            field=models.CharField(default='Informed Consent to Participate in Research', max_length=300),
        ),
    ]
