# Generated by Django 4.0.6 on 2022-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0194_consentform_agreement_text_consentform_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='submit_button_text',
            field=models.CharField(default='I consent to participate', max_length=100),
        ),
    ]
