# Generated by Django 4.0.6 on 2022-08-23 03:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0195_consentform_submit_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='consent_form_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Help Doc Text'),
        ),
    ]
