# Generated by Django 4.0.7 on 2022-09-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0199_remove_profile_consent_required_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrbStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='IRB Study Name')),
                ('number', models.CharField(max_length=100, verbose_name='IRB Study Number')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IRB Study',
                'verbose_name_plural': 'IRB Studies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='consentform',
            options={'ordering': ['name'], 'verbose_name': 'Consent Screen', 'verbose_name_plural': 'Consent Screens'},
        ),
        migrations.AddField(
            model_name='consentform',
            name='irb_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='main.irbstudy'),
        ),
    ]
