# Generated by Django 4.0.6 on 2022-09-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_irbstudy_alter_consentform_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='irb_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='main.irbstudy', verbose_name='IRB Study'),
        ),
        migrations.AlterField(
            model_name='irbstudy',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='IRB Study Name'),
        ),
        migrations.AlterField(
            model_name='irbstudy',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='IRB Study Number'),
        ),
    ]
