# Generated by Django 4.0.7 on 2022-09-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_alter_experiment_sessions_consent_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentform',
            name='IRB_ID',
        ),
    ]
