# Generated by Django 4.0.7 on 2022-09-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0206_experiment_sessions_incident_occurred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileconsentform',
            options={'ordering': ['my_profile__user__last_name', 'my_profile__user__first_name', 'timestamp'], 'verbose_name': 'Profile Consent Form', 'verbose_name_plural': 'Profile Consent Forms'},
        ),
        migrations.RemoveConstraint(
            model_name='profileconsentform',
            name='unique_profile_consent_form',
        ),
    ]
