# Generated by Django 4.0.7 on 2022-09-15 19:53

import uuid

from django.db import migrations

from main.models import profile


def update_uuids(apps, schema_editor):
    obj = [p for p in profile.objects.all()]

    for p in obj:
        p.public_id = uuid.uuid4()
    
    profile.objects.bulk_update(obj, ['public_id'])



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0209_rename_survey_id_profile_public_id'),
    ]

    operations = [
        migrations.RunPython(update_uuids),
    ]
