# Generated by Django 4.0.7 on 2022-09-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0212_experiments_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traits',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
    ]
