# Generated by Django 4.0.7 on 2022-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0213_alter_traits_description'),
    ]

    operations = [

         migrations.RenameField(
            model_name='profile',
            old_name='nonresidentAlien',
            new_name='international_student',
        ),
        migrations.AlterField(
            model_name='profile',
            name='international_student',
             field=models.BooleanField(default=False, verbose_name='Internationl Student'),
        ),
    ]
