# Generated by Django 4.2.3 on 2023-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0221_experiment_sessions_special_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrefTraits',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.traits',),
        ),
        migrations.AlterField(
            model_name='experiment_sessions',
            name='special_instructions',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
