# Generated by Django 4.2.11 on 2024-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0222_hreftraits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Multi-factor hash'),
        ),
    ]
