# Generated by Django 4.2.11 on 2024-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0223_profile_mfa_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_required',
            field=models.BooleanField(default=False, verbose_name='Multi-factor Required'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Multi-factor Hash'),
        ),
    ]
