# Generated by Django 4.2.11 on 2024-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0224_profile_mfa_required_alter_profile_mfa_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_setup_complete',
            field=models.BooleanField(default=False, verbose_name='Multi-factor Setup Complete'),
        ),
    ]
