# Generated by Django 4.2.11 on 2024-03-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0225_profile_mfa_setup_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Login Success')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('my_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_login_attempts', to='main.profile')),
            ],
            options={
                'verbose_name': 'Profile Login Attempt',
                'verbose_name_plural': 'Profile Login Attempts',
                'ordering': ['timestamp'],
            },
        ),
    ]
