# Generated by Django 4.2.11 on 2024-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0226_profileloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileloginattempt',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
