# Generated by Django 4.2.11 on 2024-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0227_profileloginattempt_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_be_pi',
            field=models.BooleanField(default=False, verbose_name='User can be a PI'),
        ),
    ]
