# Generated by Django 4.2.11 on 2024-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0228_profile_can_be_pi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_be_pi',
            new_name='pi_eligible',
        ),
    ]
