# Generated by Django 4.2.11 on 2024-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0229_rename_can_be_pi_profile_pi_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
    ]
