# Generated by Django 4.2.11 on 2024-04-03 22:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0230_profile_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Answer'),
        ),
    ]
