# Generated by Django 4.2.11 on 2024-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0231_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
