# Generated by Django 4.2.13 on 2024-06-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0234_alter_experiment_session_days_paypal_api_batch_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_types',
            new_name='AccountTypes',
        ),
    ]
