# Generated by Django 4.2.11 on 2024-06-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0243_rename_experiments_institutions_experimentsinstitutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Front_page_notice',
            new_name='FrontPageNotice',
        ),
    ]
