# Generated by Django 4.2.11 on 2024-06-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0244_rename_front_page_notice_frontpagenotice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help_docs',
            new_name='HelpDocs',
        ),
    ]
