# Generated by Django 4.2.11 on 2024-06-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0245_rename_help_docs_helpdocs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation_email_templates',
            new_name='InvitationEmailTemplates',
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
