# Generated by Django 4.2.13 on 2024-06-18 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0246_rename_invitation_email_templates_invitationemailtemplates_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_note',
            new_name='ProfileNote',
        ),
    ]
