# Generated by Django 4.2.13 on 2024-06-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0247_rename_profile_note_profilenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilenote',
            name='my_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes_a', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='profilenote',
            name='noteMaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes_b', to=settings.AUTH_USER_MODEL),
        ),
    ]
