# Generated by Django 4.2.13 on 2024-06-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0248_alter_profilenote_my_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruitment_parameters_trait_constraint',
            new_name='RecruitmentParametersTraitConstraint',
        ),
    ]
