# Generated by Django 4.2.13 on 2024-06-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0249_rename_recruitment_parameters_trait_constraint_recruitmentparameterstraitconstraint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recruitment_parameters',
            new_name='RecruitmentParameters',
        ),
    ]
