# Generated by Django 4.2.13 on 2024-06-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0250_rename_recruitment_parameters_recruitmentparameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subject_types',
            new_name='SubjectTypes',
        ),
    ]
