# Generated by Django 5.2.14 on 2026-06-01 18:44

import django.db.models.deletion
from django.db import migrations, models


def initSexes(apps, schema_editor):
    Sexes = apps.get_model('main', 'sexes')

    entries = [
        (1, 'Prefer not to say'),
        (2, 'Male'),
        (3, 'Female'),
        (4, 'Intersex'),
    ]

    for sex_id, name in entries:
        Sexes.objects.update_or_create(
            id=sex_id,
            defaults={
                'name': name,
                'initialValue': True,
            },
        )


def reverseNoop(apps, schema_editor):
    pass


def populateRecruitmentParametersSexes(apps, schema_editor):
    Sexes = apps.get_model('main', 'sexes')
    RecruitmentParameters = apps.get_model('main', 'recruitmentparameters')

    all_sex_ids = list(Sexes.objects.values_list('id', flat=True))

    for recruitment_parameters in RecruitmentParameters.objects.all().iterator():
        recruitment_parameters.sex.set(all_sex_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0254_rename_email_ms_auth_access_token_parameters_email_ms_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('initialValue', models.BooleanField(default=True, verbose_name='Default to On')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sex',
                'verbose_name_plural': 'Sexes',
            },
        ),
        migrations.RunPython(initSexes, reverseNoop),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sexes', verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='sex',
            field=models.ManyToManyField(to='main.sexes'),
        ),
        migrations.RunPython(populateRecruitmentParametersSexes, reverseNoop),
    ]
