# Generated by Django 2.2.10 on 2020-06-16 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200616_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_days',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 23, 12, 18, 153842, tzinfo=utc)),
        ),
    ]
