# Generated by Django 3.0.7 on 2020-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200706_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_session_day_users',
            name='earnings',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='experiment_session_day_users',
            name='show_up_fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
