# Generated by Django 3.0.7 on 2020-07-31 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_recruitmentparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_session_invitations',
            name='recruitmentParams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recruitmentParameters'),
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentparameters',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
