# Generated by Django 3.0.7 on 2020-08-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20200811_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiments',
            old_name='recruitmentParams',
            new_name='recruitmentParamsDefault',
        ),
    ]
