# Generated by Django 3.0.7 on 2020-08-14 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0056_auto_20200812_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='noShowCutoff',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='parameters',
            name='noShowCutoffWindow',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blackballed',
            field=models.BooleanField(default=False, verbose_name='Blackballed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chapmanID',
            field=models.CharField(default='00000000', max_length=100, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emailConfirmed',
            field=models.CharField(default='no', max_length=100, verbose_name='Email Confirmed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.genders', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.majors', verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.schools', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentWorker',
            field=models.BooleanField(default=False, verbose_name='Student Woker'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjectType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subject_types', verbose_name='Subject Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.accountTypes', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
