# Generated by Django 3.0.7 on 2020-08-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200822_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfilter',
            name='name',
        ),
    ]
