# Generated by Django 3.0.7 on 2020-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20200823_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='emailFilter',
            field=models.ManyToManyField(blank=True, to='main.emailFilters', verbose_name='Email Filters'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
