# Generated by Django 3.0.7 on 2020-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20200917_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_session_days',
            name='confirmationEmailSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameters',
            name='reminderTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='reminderTextText',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
