# Generated by Django 3.0.7 on 2020-09-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_experiments_remindertext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_session_days',
            old_name='confirmationEmailSent',
            new_name='reminderEmailSent',
        ),
    ]
