# Generated by Django 3.0.7 on 2020-09-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20200917_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='siteURL',
            field=models.CharField(default='https://www.google.com/', max_length=200),
        ),
    ]
