# Generated by Django 2.2.10 on 2020-06-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200617_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gradStudent',
        ),
        migrations.AddField(
            model_name='profile',
            name='subjectType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subject_types'),
        ),
        migrations.AlterField(
            model_name='experiment_sessions',
            name='experience_level',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='main.experience_levels'),
        ),
    ]
