# Generated by Django 3.0.7 on 2020-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200717_1631'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='experiment_session_day_users',
            constraint=models.UniqueConstraint(fields=('user', 'experiment_session_day'), name='unique_ESDU'),
        ),
    ]
