# Generated by Django 3.0.7 on 2020-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200724_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_sessions',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
