# Generated by Django 3.0.7 on 2020-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_experiment_session_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_session_messages',
            name='mailResultErrorText',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='experiment_session_messages',
            name='mailResultSentCount',
            field=models.IntegerField(default=0),
        ),
    ]
