# Generated by Django 3.0.7 on 2020-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_experiment_session_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitmentParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_participants', models.IntegerField(default=1)),
                ('registration_cutoff', models.IntegerField(default=1)),
                ('experience_min', models.IntegerField(default=0)),
                ('experience_max', models.IntegerField(default=1000)),
                ('experience_constraint', models.BooleanField(default=False)),
                ('institutions_exclude_all', models.BooleanField(default=True)),
                ('institutions_include_all', models.BooleanField(default=True)),
                ('experiments_exclude_all', models.BooleanField(default=True)),
                ('experiments_include_all', models.BooleanField(default=True)),
                ('allow_multiple_participations', models.BooleanField(default=False)),
                ('experiments_exclude', models.ManyToManyField(blank=True, related_name='recruitmentparameters_experiments_exclude', to='main.experiments')),
                ('experiments_include', models.ManyToManyField(blank=True, related_name='recruitmentparameters_experiments_include', to='main.experiments')),
                ('gender', models.ManyToManyField(to='main.genders')),
                ('institutions_exclude', models.ManyToManyField(blank=True, related_name='recruitmentparameters_institutions_exclude', to='main.institutions')),
                ('institutions_include', models.ManyToManyField(blank=True, related_name='recruitmentparameters_institutions_include', to='main.institutions')),
                ('subject_type', models.ManyToManyField(to='main.subject_types')),
            ],
            options={
                'verbose_name': 'Recruitment Parameters',
                'verbose_name_plural': 'Recruitment Parameters',
            },
        ),
    ]
