# Generated by Django 3.0.7 on 2020-07-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200731_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='actual_participants',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='allow_multiple_participations',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experience_constraint',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experience_max',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experience_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experiments_exclude_all',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='experiments_include_all',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='institutions_exclude_all',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='institutions_include_all',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentparameters',
            name='registration_cutoff',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
