# Generated by Django 3.0.7 on 2020-08-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20200826_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='school_legacy',
        ),
    ]
