# Generated by Django 3.0.7 on 2020-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_experiment_session_day_users_manuallyadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='genders',
            name='intialValue',
            field=models.BooleanField(default=False),
        ),
    ]
