# Generated by Django 3.0.7 on 2020-09-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0090_parameters_siteurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emailFilters',
            new_name='email_filters',
        ),
    ]
