# Generated by Django 3.0.7 on 2020-09-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20200919_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment_session_invitations',
            old_name='recruitmentParams',
            new_name='recruitment_params',
        ),
        migrations.RenameField(
            model_name='experiment_sessions',
            old_name='recruitmentParams',
            new_name='recruitment_params',
        ),
    ]
