# Generated by Django 3.0.7 on 2020-09-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20200919_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailConfirmed',
            new_name='email_confirmed',
        ),
    ]
