# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - chapman-experiments

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        env:
          ALLOWED_HOSTS: localhost 127.0.0.1
          CSRF_TRUSTED_ORIGINS : http://localhost
          DBHOST: localhost
          DBNAME: github_actions
          DBPASS: postgres
          DBUSER: postgres
          LOG_LOCATION: abc
          MEDIA_ROOT : abc
          STATIC_ROOT : abe
          STATIC_URL : abc/
          AZURE_CONTAINER : abc
          AZURE_ACCOUNT_NAME : abc
          AZURE_ACCOUNT_KEY : abc
          AZURE_CUSTOM_DOMAIN : abc
          EMAIL_MS_HOST: ${{ secrets.TEST_EMAIL_MS_HOST }}
          EMAIL_MS_USER_NAME: ${{ secrets.TEST_EMAIL_MS_USER_NAME }}
          EMAIL_MS_PASSWORD: ${{ secrets.TEST_EMAIL_MS_PASSWORD }}
          PPMS_HOST : ${{ secrets.TEST_PPMS_HOST }}
          PPMS_USER_NAME : ${{ secrets.TEST_PPMS_PASSWORD }}
          PPMS_PASSWORD : ${{ secrets.TEST_EMAIL_MS_HOST }}
          SECRET_KEY: super_duper_secret_key
        run: python manage.py test
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: '${{ secrets.APP_NAME }}'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_63AA5C73EB444745ACB2DED683193A07 }}
